name: magikarp
version: "v0.1.0"
providers:
  anthropic:
    models: [claude-3-5-sonnet-20240620, claude-3-5-haiku-20240307, claude-3-5-opus-20240229] 
    temperature: 0.7
    key: ${ANTHROPIC_API_KEY}
  openai:
    models: [o1-mini, o1-preview, gpt-4o, gpt-4o-mini, gpt-o3-mini, gpt-o3-mini-high]
    temperature: 0.7
    key: ${OPENAI_API_KEY}
  gemini:
    models: [gemini-pro, gemini-pro-vision]
    temperature: 0.7
    key: ${GEMINI_API_KEY}
system: "You are a helpful coding assistant."
speech:
  model_path: ~/.magikarp/models/ggml-small.en.bin
  sample_rate: 16000
  keyword: "over"
  enabled: true
