version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    ports:
      - 8000:8000
    volumes:
      - .:/app
    command: ["fastapi", "run", "magikarp/main.py", "--host", "0.0.0.0", "--port", "8000"]
    restart: always
    depends_on:
      - ollama
    networks:
      - ollama-docker
    environment:
      - OLLAMA_HOST=http://ollama:11434

  ollama:
    image: ollama/ollama:latest
    ports:
      - 11434:11434
    volumes:
      - ./ollama/ollama:/root/.ollama
      - ./entrypoint.sh:/entrypoint.sh
      - ./Modelfile:/app/Modelfile
    container_name: ollama
    pull_policy: always
    tty: true
    entrypoint: ["/usr/bin/bash", "/entrypoint.sh"]
    restart: always
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0
    networks:
      - ollama-docker

networks:
  ollama-docker:
